(() => {
  'use strict';
  const rail=document.querySelector('#work-grid'),slides=[...rail.querySelectorAll('.solution-slide')],sectors=[...document.querySelectorAll('[data-gallery-target]')];
  const previous=document.querySelector('#gallery-prev'),next=document.querySelector('#gallery-next');
  const defaults={food:[{id:'014',name:'2 xis salada',detail:'Retirada · sem cebola',stage:0},{id:'015',name:'Pizza média',detail:'Entrega · massa fina',stage:1},{id:'016',name:'À la minuta',detail:'Salão · mesa 04',stage:2}],clinic:[{time:'09:00',id:'Solicitação 01',status:'A confirmar'},{time:'10:30',id:'Solicitação 02',status:'Confirmada'},{time:'14:00',id:'Solicitação 03',status:'A confirmar'}],garage:[{id:'OS 041',name:'Revisão de exemplo',detail:'Peças em avaliação',stage:0},{id:'OS 042',name:'Manutenção de exemplo',detail:'Serviço em andamento',stage:1},{id:'OS 043',name:'Ajuste de exemplo',detail:'Retirada a combinar',stage:2}],stock:[{name:'Arroz 5 kg',sku:'PRD 021',quantity:3,min:8,listed:false},{name:'Leite 1 L',sku:'PRD 022',quantity:6,min:12,listed:false},{name:'Sabão 500 g',sku:'PRD 023',quantity:14,min:10,listed:false}],docs:[['Referência','DOC-028'],['Tipo','Contrato de exemplo'],['Data','10/10/2026'],['Prazo de revisão','15/10/2026'],['Situação','Aguardando conferência']],android:[{title:'Revisar pedido de orçamento',done:true},{title:'Conferir entrega de exemplo',done:false},{title:'Organizar arquivos do dia',done:false}]};
  let data=structuredClone(defaults),docQuery='',current=0,drag=null;
  const titles={food:'Painel de pedidos',clinic:'Agenda da recepção',garage:'Ordens de serviço',stock:'Estoque & reposição',docs:'Documentos & campos',android:'Minha rotina'};
  const hosts=Object.fromEntries([...document.querySelectorAll('[data-demo]')].map(e=>[e.dataset.demo,e]));
  const footer=(key,message)=>`<div class="demo-footer"><button class="demo-reset" type="button" data-reset="${key}">↺ Restaurar exemplo</button><span class="demo-feedback" role="status" aria-live="polite">${message}</span></div>`;
  const head=(title,count)=>`<div class="preview-heading"><div><small>EXEMPLO DA ROTINA</small><h4>${title}</h4></div><span class="preview-count">${count}</span></div>`;
  const shell=(key,body)=>`<div class="preview-window"><div class="preview-bar"><span class="preview-app"><img src="jhou-mark.ico" alt="">${titles[key]}</span><span class="demo-badge">DEMONSTRAÇÃO</span></div><div class="preview-body">${body}</div></div>`;
  function render(key,message='Teste os controles do exemplo.'){
    let body='';
    if(key==='food'||key==='garage'){
      const stages=key==='food'?['Recebido','Em preparo','Pronto']:['Recebido','Em serviço','Finalizado'];
      body=head(key==='food'?'O movimento de hoje':'Serviços em andamento','3 registros')+data[key].map((r,i)=>`<div class="demo-order"><div><span class="record-id">${key==='food'?'PEDIDO ':''}${r.id}</span><strong>${r.name}</strong><p>${r.detail}</p></div><div class="record-action"><span class="stage-pill" data-stage="${r.stage}">${stages[r.stage]}</span>${r.stage<2?`<button type="button" class="demo-action" data-advance="${key}" data-index="${i}">${r.stage===0?(key==='food'?'Preparar':'Iniciar'):'Concluir'} →</button>`:'<span class="stage-pill" data-stage="2">✓ Concluído</span>'}</div></div>`).join('')+footer(key,message);
    }else if(key==='clinic'){
      const confirmed=data.clinic.filter(r=>r.status==='Confirmada').length;
      body=head('Horários em acompanhamento',`${confirmed} de 3 confirmados`)+data.clinic.map((r,i)=>`<div class="schedule-row"><time>${r.time}</time><div><strong>${r.id}</strong><small>Registro administrativo fictício</small></div><div class="schedule-state"><span class="stage-pill" data-stage="${r.status==='Confirmada'?2:0}">${r.status}</span>${r.status!=='Confirmada'?`<button type="button" class="demo-action" data-confirm="${i}">Confirmar</button>`:''}</div></div>`).join('')+footer(key,message);
    }else if(key==='stock'){
      const low=data.stock.filter(r=>r.quantity<r.min).length,listed=data.stock.filter(r=>r.listed).length;
      body=head('O que precisa repor?','3 produtos')+`<div class="stock-meters"><div>Abaixo do mínimo<b>${low}</b></div><div>Na lista de reposição<b>${listed}</b></div></div>`+data.stock.map((r,i)=>`<div class="stock-row"><div><strong>${r.name}</strong><small>${r.sku} · mínimo ${r.min}</small></div><span class="stock-level">${r.quantity}<small> unidades</small></span><button type="button" class="demo-action" data-replenish="${i}"${r.listed?' disabled':''}>${r.listed?'✓ Na lista':'Adicionar'}</button></div>`).join('')+footer(key,message);
    }else if(key==='docs'){
      const rows=data.docs.filter(r=>r.join(' ').toLocaleLowerCase('pt-BR').includes(docQuery.toLocaleLowerCase('pt-BR')));
      body=head('Do documento para o dado',`${rows.length} ${rows.length===1?'campo':'campos'}`)+`<label class="document-search">Buscar no exemplo<input type="search" data-document-search placeholder="Ex.: prazo, data, contrato" value=""></label><div class="document-results">${rows.length?rows.map(([label,value])=>`<div class="document-row"><span>${label}</span><strong>${value}</strong></div>`).join(''):'<p class="empty-demo">Nenhum campo encontrado neste exemplo.</p>'}</div><p class="document-source">Fonte ilustrativa: documento-de-exemplo.pdf · página 01</p>`+footer(key,message);
    }else if(key==='android'){
      const done=data.android.filter(r=>r.done).length;
      hosts[key].innerHTML=`<div class="mobile-preview"><div class="phone-demo"><div class="phone-sensor" aria-hidden="true"></div><div class="phone-head"><span>Minha rotina</span><img src="jhou-mark.ico" alt=""></div><h4>Um passo<br>de cada vez.</h4><p>As tarefas de hoje, onde tu estiver.</p><div class="phone-progress"><div><span>Concluídas</span><strong>${done} / 3</strong></div><div class="task-bar" aria-hidden="true"><i style="width:${done/3*100}%"></i></div></div>${data.android.map((r,i)=>`<label class="phone-task${r.done?' is-done':''}"><input type="checkbox" data-task="${i}"${r.done?' checked':''}><span>${r.title}</span></label>`).join('')}${footer(key,message)}</div><div class="mobile-note">Teu trabalho.<br>No teu bolso.<small>Agenda, tarefas e registros.<br>Uma ideia de app Android.</small></div></div>`;
      return;
    }
    hosts[key].innerHTML=shell(key,body);
  }
  Object.keys(hosts).forEach(key=>render(key));
  rail.addEventListener('click',event=>{
    const button=event.target.closest('button');if(!button)return;
    if(button.dataset.advance){const key=button.dataset.advance,index=Number(button.dataset.index);data[key][index].stage=Math.min(2,data[key][index].stage+1);render(key,'Etapa atualizada no exemplo.');(hosts[key].querySelector(`[data-advance][data-index="${index}"]`)||hosts[key].querySelector('[data-reset]')).focus({preventScroll:true});}
    if(button.dataset.confirm!==undefined){data.clinic[Number(button.dataset.confirm)].status='Confirmada';render('clinic','Horário confirmado no exemplo.');hosts.clinic.querySelector('[data-reset]').focus({preventScroll:true});}
    if(button.dataset.replenish!==undefined){data.stock[Number(button.dataset.replenish)].listed=true;render('stock','Produto adicionado à lista de exemplo.');hosts.stock.querySelector('[data-reset]').focus({preventScroll:true});}
    if(button.dataset.reset){const key=button.dataset.reset;data[key]=structuredClone(defaults[key]);if(key==='docs')docQuery='';render(key,'Exemplo restaurado.');hosts[key].querySelector('[data-reset]').focus({preventScroll:true});}
  });
  rail.addEventListener('change',event=>{if(event.target.dataset.task!==undefined){const index=Number(event.target.dataset.task);data.android[index].done=event.target.checked;render('android','Lista atualizada no exemplo.');hosts.android.querySelector(`[data-task="${index}"]`).focus({preventScroll:true});}});
  rail.addEventListener('input',event=>{if(event.target.dataset.documentSearch===undefined)return;docQuery=event.target.value;const rows=data.docs.filter(r=>r.join(' ').toLocaleLowerCase('pt-BR').includes(docQuery.toLocaleLowerCase('pt-BR')));const region=hosts.docs.querySelector('.document-results');region.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='empty-demo';p.textContent='Nenhum campo encontrado neste exemplo.';region.append(p);}else rows.forEach(([label,value])=>{const row=document.createElement('div'),name=document.createElement('span'),result=document.createElement('strong');row.className='document-row';name.textContent=label;result.textContent=value;row.append(name,result);region.append(row);});hosts.docs.querySelector('.preview-count').textContent=`${rows.length} ${rows.length===1?'campo':'campos'}`;});
  const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  function update(){current=slides.reduce((best,slide,index)=>Math.abs(slide.offsetLeft-rail.scrollLeft)<Math.abs(slides[best].offsetLeft-rail.scrollLeft)?index:best,0);slides.forEach((slide,index)=>slide.inert=index!==current);sectors.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.galleryTarget===slides[current].dataset.key)));document.querySelector('#gallery-position').textContent=`${String(current+1).padStart(2,'0')} / 06`;document.querySelector('#gallery-current').textContent=slides[current].dataset.title;document.querySelector('.rail-progress i').style.width=`${(current+1)/6*100}%`;previous.disabled=current===0;next.disabled=current===slides.length-1;}
  function go(index){const target=slides[Math.max(0,Math.min(slides.length-1,index))];rail.scrollTo({left:target.offsetLeft,behavior:reduced()?'auto':'smooth'});}
  previous.addEventListener('click',()=>go(current-1));next.addEventListener('click',()=>go(current+1));
  sectors.forEach(b=>b.addEventListener('click',()=>go(slides.findIndex(s=>s.dataset.key===b.dataset.galleryTarget))));
  rail.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',()=>{go(current);update();});
  rail.addEventListener('keydown',event=>{if(event.target!==rail)return;if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();go(current+(event.key==='ArrowRight'?1:-1));}else if(event.key==='Home'||event.key==='End'){event.preventDefault();go(event.key==='Home'?0:slides.length-1);}});
  rail.addEventListener('pointerdown',event=>{if(event.pointerType!=='mouse'||event.button!==0||event.target.closest('button,a,input,label'))return;drag={id:event.pointerId,x:event.clientX,left:rail.scrollLeft,moved:false};});
  rail.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.id)return;const delta=event.clientX-drag.x;if(!drag.moved&&Math.abs(delta)>8){drag.moved=true;rail.classList.add('is-dragging');rail.setPointerCapture(event.pointerId);}if(drag.moved){event.preventDefault();rail.scrollLeft=drag.left-delta;}});
  function finish(event){if(!drag||event.pointerId!==drag.id)return;const moved=drag.moved;drag=null;rail.classList.remove('is-dragging');if(rail.hasPointerCapture(event.pointerId))rail.releasePointerCapture(event.pointerId);if(moved){update();go(current);}}
  rail.addEventListener('pointerup',finish);rail.addEventListener('pointercancel',finish);rail.addEventListener('pointerleave',()=>{if(drag&&!drag.moved)drag=null;});rail.addEventListener('dragstart',event=>event.preventDefault());
  update();
})();
